/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ballboy;


import org.junit.Test;

public class AppTest {

    @Test
    public void setupTest(){
        App.main(new String[]{"test"});
    }
}
